#! /usr/bin/env python3

####################################################################################################
#
# A uv tool to show package size on disk
#   https://github.com/astral-sh/uv/issues/17884
#
# Copyright (C) 2026 Fabrice SALVAIRE
# SPDX-License-Identifier: AGPL-3.0-or-later
#
####################################################################################################

# Notes:
#   each package as an entry (directory) per Python version in archive-v0
#   the directory has the same content for a pure Python package
#   but the directory inode is different ! Thus it is duplicated ???

####################################################################################################

import argparse
import os
from pathlib import Path

from rich.console import Console

####################################################################################################

CACHE_DIR = Path.home().joinpath('.cache', 'uv')

####################################################################################################

C = Console()

####################################################################################################

def human_size(size: int) -> str:
    size_suffixes = (' ', 'k', 'M', 'G')
    size_suffix = 0
    _: float = size
    while _ > 1024:
        _ /= 1024
        size_suffix += 1
    suffix = size_suffixes[size_suffix]
    match suffix:
        case 'M' | 'G':
            return f'{_:.1f} {suffix}B'
        case _:
            return '< MB'

####################################################################################################

class PathInode:
    """Convenient class to information like disk usage for a path."""

    ##############################################

    def __init__(self, path: Path) -> None:
        self._path = Path(path)
        self._stat: os.stat_result | None = None

    ##############################################

    def __str__(self) -> str:
        return str(self._path)

    ##############################################

    @property
    def stat(self) -> os.stat_result:
        if self._stat is None:
            # self._stat = self._path.stat(follow_symlinks=False)
            self._stat = os.lstat(str(self._path))
        return self._stat

    ##############################################

    @property
    def inode(self) -> int:
        return self.stat.st_ino

    ##############################################

    @property
    def is_hardlink(self) -> bool:
        return self.stat.st_nlink > 1

    ##############################################

    @property
    def disk_size(self) -> int:
        # size += _.stat().st_size
        # allocated
        return self.stat.st_blocks * 512

####################################################################################################

def disk_size(path: Path) -> int:
    """Return the disk size of path in bytes.

    Hardlinked inodes are counted once.
 
   """
    size = 0
    inodes: set[int] = set()

    def accumulate(path: Path) -> None:
        file = PathInode(path)
        inode = file.inode
        if inode not in inodes:
            nonlocal size
            size += file.disk_size
        # else:
        #     C.print(f"hardlink duplicate {file}")
        inodes.add(inode)

    accumulate(path)
    for root, dirnames, filenames in path.walk():
        for _ in dirnames:
            accumulate(root / _)
        for _ in filenames:
            accumulate(root / _)
    return size

####################################################################################################

class UvCacheMixin:

    ##############################################

    def __init__(self, path: Path) -> None:
        self.path = path
        with C.status(f"Computing {self.path} size..."):
            self.size = disk_size(self.path)

####################################################################################################

class UvCache(UvCacheMixin):

    ##############################################

    def __init__(self, path: Path) -> None:
        super().__init__(path)
        C.print(f"UV Cache is: {CACHE_DIR}   {human_size(self.size)}")
        for _ in sorted(self.path.iterdir()):
            if _.is_dir() and _.name[0] != '.':
                UvCacheDirectory(_)

####################################################################################################

class UvCacheDirectory(UvCacheMixin):

    ##############################################

    def __init__(self, path: Path) -> None:
        super().__init__(path)
        C.print(f"{self.path.name:16} {human_size(self.size):>10}")

        size_accumulator = 0
        name = self.path.name
        if name.startswith('sdist'):
            path = self.path / 'pypi'
            with C.status(f"Computing {path} size..."):
                # Fixme: bucket: editable git path
                for _ in sorted(path.iterdir()):
                    # /package_name/version/uuid/
                    #   package-version-cp315-cp315-linux_x86_64 symlink to archive-v0/uuid
                    #   package-version-cp315-cp315-linux_x86_64.whl
                    #   src
                    size = disk_size(_)
                    size_accumulator += size
                    C.print(f"    {_.name:30} {human_size(size):>10}   [yellow]{human_size(size_accumulator):>10}")
        elif name.startswith('archive'):
            # archive-v0/uuid/
            #   package/
            #   package-version.data/
            #   package-version.dist-info/
            packages = [Package(_) for _ in self.path.iterdir() if _.is_dir()]
            # for _ in sorted(packages, key=lambda _: _.name):
            for _ in sorted(packages, key=lambda _: _.size):
                size_accumulator += _.size
                C.print(f"    {_.name:30} {_.version:16} {human_size(_.size):>10}   [yellow]{human_size(size_accumulator):>10}")
        # if size_accumulator:
        #     C.print(f"  [yellow]Size accumulator: {human_size(size_accumulator)}")

####################################################################################################

class Package(UvCacheMixin):
    """Implements a Python Package"""

    VERSION_MAP: dict[str, list[str]] = {}

    ##############################################

    def __init__(self, path: Path) -> None:
        # compute disk size
        # get version and name
        super().__init__(path)
        # Get package name and version from name-version.dist-info filename
        # Register to VERSION_MAP
        # Fixme:
        self.name = '???'
        self.version = '???'
        name_version = None
        SUFFIX = '.dist-info'
        for _ in self.path.iterdir():
            name = _.name
            if name.endswith(SUFFIX):
                name_version = name[:-len(SUFFIX)]
        if name_version is not None:
            i = name_version.rfind('-')
            if i != -1:
                self.name = name_version[:i]
                self.version = name_version[i+1:]
                self.VERSION_MAP.setdefault(self.name, [])
                self.VERSION_MAP[self.name].append(self.version)
            else:
                C.print(f"[red]WARNING: unsupported version for {self.path}")
        else:
            # Fixme:
            #   /home/fabrice/.cache/uv/archive-v0/jnmE0T_XlOGz8rOhVrFja/bin/python3.13
            C.print(f"[red]WARNING: dist-info not found for {self.path}")

####################################################################################################

def cache_size_command() -> None:
    uv_cache = UvCache(CACHE_DIR)
    C.print()
    C.print('Packages with several versions:')
    C.print('  (duplicates corresponds to different cpython)')
    C.print()
    for name in sorted(Package.VERSION_MAP):
        versions = sorted(Package.VERSION_MAP[name])
        if len(versions) > 1:
            C.print(f"  {name:32} {versions}")

####################################################################################################

def find_venv_command(path: Path | str) -> None:
    path = Path(path)
    for root, dirnames, filenames in path.walk():
        dirnames.sort()   # Fixme: unicode
        if root.name == '.venv':
            C.print(root)
        for filename in sorted(filenames):
            match filename:
                case 'uv.lock':
                    pass
                case '.python-version':
                    pass

####################################################################################################

parser = argparse.ArgumentParser(
    prog='uv-cache-tool',
    description='',
    epilog='',
)
parser.add_argument(
    '--cache-size',
    action='store_true',
)
parser.add_argument(
    '--find-venv',
)
args = parser.parse_args()

####################################################################################################

if args.cache_size:
    cache_size_command()
elif args.find_venv:
    find_venv_command(args.find_venv)
else:
    parser.print_help()
