#! /usr/bin/env python3

####################################################################################################
#
# A uv tool to show package size on disk
#   https://github.com/astral-sh/uv/issues/17884
#
# Copyright (C) 2026 Fabrice SALVAIRE
# SPDX-License-Identifier: AGPL-3.0-or-later
#
####################################################################################################

# Notes:
#   .venv/lib/python3.15/site-packages/package are hardlinked to ~/.cave/uv/archive-v0/uuid/package
#   to remove effectively a package we must delete it in the .venv and then prune the cache !
#
#   each package as an entry (directory) per Python version in archive-v0
#   the directory has the same content for a pure Python package
#   but the directory inode is different ! Thus it is duplicated ???

# uv lock --upgrade
#  upgrade everything
# uv sync --upgrade-package

# hardlink count
#   file >= 1
#   directory >= 2

####################################################################################################

import argparse
import json
import os
import re
import subprocess
from collections.abc import Iterator
from pathlib import Path
from typing import cast

from rich.console import Console

####################################################################################################

CACHE_DIR = Path.home().joinpath('.cache', 'uv')

TO_UPDATE = [
    'invoke',
    'ipython',
    'pyyaml',
    'rassumfrassum',
    'rich',
    'ruff',
    'ty',
    'uv_build',
    'requests',
]

C = Console()

####################################################################################################

def human_size(size: int, min_suffix: str = 'M') -> str:
    SUFFIXES = (' ', 'k', 'M', 'G', 'T')
    suffix_index = 0
    _: float = size
    while _ > 1024:
        _ /= 1024
        suffix_index += 1
    if suffix_index >= SUFFIXES.index(min_suffix):
        suffix = SUFFIXES[suffix_index]
        return f'{_:.1f} {suffix}B'
    else:
        suffix = SUFFIXES[suffix_index + 1]
        return f'< {suffix}B'

####################################################################################################

class PathInode:
    """Convenient class to information like disk usage for a path."""

    ##############################################

    def __init__(self, path: Path) -> None:
        self._path = Path(path)
        self._stat: os.stat_result | None = None  # lazy

    ##############################################

    def __str__(self) -> str:
        return str(self._path)

    ##############################################

    @property
    def stat(self) -> os.stat_result:
        if self._stat is None:
            # self._stat = self._path.stat(follow_symlinks=False)
            self._stat = os.lstat(str(self._path))
        return self._stat

    ##############################################

    @property
    def inode(self) -> int:
        return self.stat.st_ino

    ##############################################

    @property
    def nlink(self) -> int:
        return self.stat.st_nlink

    @property
    def is_hardlink(self) -> bool:
        return self.nlink > 1

    ##############################################

    @property
    def disk_size(self) -> int:
        # size += _.stat().st_size
        # allocated
        return self.stat.st_blocks * 512

####################################################################################################

def disk_size(path: Path) -> int:
    """Return the disk size of path in bytes.

    Hardlinked inodes are counted once.

   """
    size = 0
    inodes: set[int] = set()

    def accumulate(path: Path) -> None:
        file = PathInode(path)
        inode = file.inode
        if inode not in inodes:
            nonlocal size
            size += file.disk_size
        # else:
        #     C.print(f"hardlink duplicate {file}")
        inodes.add(inode)

    accumulate(path)
    for root, dirnames, filenames in path.walk():
        for item in (dirnames, filenames):
            for _ in item:
                accumulate(root / _)
    return size

####################################################################################################

class UvCacheMixin:

    ##############################################

    def __init__(self, path: Path) -> None:
        # print(f"Path {path}")
        self.path = path
        self._size: int | None = None  # lazy

    ##############################################

    @property
    def size(self) -> int:
        if self._size is None:
            with C.status(f"Computing {self.path} size..."):
                self._size = disk_size(self.path)
        return self._size

####################################################################################################

class UvCache(UvCacheMixin):

    ##############################################

    def __init__(self, path: Path) -> None:
        super().__init__(path)
        self.packages: dict[str, Package] = {}
        self._scan_archive()
        self.sdist_packages: dict[str, Package] = {}
        self._scan_sdist()

    ##############################################

    def list(self) -> None:
        def print_directory(directory: dict[str, Package]) -> None:
            for package in sorted(directory.values(), key=lambda _: _.name):
                C.print(f"[blue]{package.name}")
                for version in package:
                    path = str(version.path.relative_to(CACHE_DIR))
                    nlink = version.nlink if isinstance(version, ArchivePackage) else '---'
                    C.print(f"  v{version.version:<24} @{version.py_version}   {path:<30}  #{nlink}")

        C.rule()
        C.print("[red]SDist Packages")
        print_directory(self.sdist_packages)
        C.rule()
        C.print("[red]Packages")
        print_directory(self.packages)

    ##############################################

    def compute_size(self, min_size: int = 0) -> None:
        C.print(f"UV Cache is: {CACHE_DIR}   {human_size(self.size)}")
        self.directories: dict[str, UvCacheDirectory] = {}
        for subdir_path in sorted(self.path.iterdir()):
            if subdir_path.is_dir() and subdir_path.name[0] != '.':
                directory = UvCacheDirectory(subdir_path)
                self.directories[directory.name] = directory
                C.print(f"  {directory.path.name:16} {human_size(directory.size):>10}")

        def sort_key_by_name(_: Package) -> str:
            return _.name

        def sort_key_by_size(_: Package) -> int:
            return _.size

        def print_directory(directory: dict[str, Package]) -> None:
            sort_key = sort_key_by_size
            packages = sorted(directory.values(), key=sort_key)
            for package in packages:
                size = package.size
                if size < min_size:
                    continue
                C.print(f"[blue]{package.name:<28} {human_size(size):>10}")
                for package_version in cast(Iterator[SdistPackage], package):
                    version = package_version.version
                    py_version = str(package_version.py_version)
                    size = package_version.size
                    path = package_version.path.relative_to(CACHE_DIR)
                    C.print(f"  v{version:<12} @{py_version:<8} {human_size(size):>13}   {path}")

        C.rule()
        C.print("[red]SDist Packages")
        print_directory('sdist-v9', self.sdist_packages)
        C.rule()
        C.print("[red]Packages")
        print_directory(self.packages)

    ##############################################

    def _scan_archive(self) -> None:
        path = self.path / 'archive-v0'
        packages = [ArchivePackage(_) for _ in path.iterdir() if _.is_dir()]
        for package in packages:
            self.packages.setdefault(package.name, Package(package.name)).add_version(package)

    ##############################################

    def _scan_sdist(self) -> None:
        path = self.path / 'sdists-v9'
        # Fixme: bucket: editable git path
        packages = [
            SdistPackage(version)
            for package in (path / 'pypi').iterdir()
            for version in package.iterdir()
        ]
        # Fixme: duplicated code
        for package in packages:
            self.sdist_packages.setdefault(package.name, Package(package.name)).add_version(package)

####################################################################################################

class UvCacheDirectory(UvCacheMixin):

    ##############################################

    def __init__(self, path: Path) -> None:
        super().__init__(path)

    ##############################################

    @property
    def name(self) -> str:
        return self.path.name

####################################################################################################

class PackageVersion(UvCacheMixin):

    ##############################################

    def __init__(self, path: Path, name: str, version: str) -> None:
        super().__init__(path)
        self.name = name
        self.version = version
        self.py_version: str | None = self._get_py_version()

    ##############################################

    def _get_py_version(self) -> str | None:
        return None

####################################################################################################

class Package:

    ##############################################

    def __init__(self, name: str) -> None:
        self.name = name
        self._versions: list[PackageVersion] = []

    ##############################################

    def __len_(self) -> int:
        return len(self._versions)

    def __iter__(self) -> Iterator[PackageVersion]:
        return iter(sorted(self._versions, key=lambda _: f'{_.version}-{_.py_version}'))

    ##############################################

    def add_version(self, version: PackageVersion) -> None:
        self._versions.append(version)

    ##############################################

    @property
    def versions(self) -> list[str]:
        return [_.version for _ in self]

    @property
    def versions_count(self) -> list[tuple[str, int]]:
        versions = self.versions
        return [(_, versions.count(_)) for _ in set(versions)]

    @property
    def size(self) -> int:
        return sum(_.size for _ in self._versions)

####################################################################################################

class ArchivePackage(PackageVersion):
    """Implements a Python Package"""

    # archive-v0/uuid/
    #   package/
    #   package-version.data/
    #   package-version.dist-info/

    ##############################################

    @classmethod
    def _get_name_version(cls, path: Path) -> tuple[str, str]:
        # Get package name and version from name-version.dist-info filename
        # Fixme:
        name = ''
        version = ''
        name_version = None
        SUFFIX = '.dist-info'
        for _ in path.iterdir():
            name = _.name
            if name.endswith(SUFFIX):
                name_version = name[:-len(SUFFIX)]
        if name_version is not None:
            i = name_version.rfind('-')
            if i != -1:
                name = name_version[:i]
                version = name_version[i+1:]
            else:
                C.print(f"[red]WARNING: unsupported version for {path}")
        else:
            # Fixme:
            #   /home/fabrice/.cache/uv/archive-v0/jnmE0T_XlOGz8rOhVrFja/bin/python3.13
            C.print(f"[red]WARNING: dist-info not found for {path}")
        if not (name and version):
            raise ValueError(f"Cannot retrieve name and version for {path}")
        return name, version

    ##############################################

    def __init__(self, path: Path) -> None:
        # get version and name
        # Register to VERSION_MAP
        name, version = self._get_name_version(path)
        super().__init__(path, name, version)
        self._nlink: int | None = None  # lazy

    ##############################################

    def _get_py_version(self) -> str | None:
        SUFFIX = '.so'
        so_file = None
        for root, dirnames, filenames in self.path.walk():
            for filename in filenames:
                if filename.endswith(SUFFIX):
                    so_file = filename
                    break
        if so_file is not None:
            match = re.match(r'^.*\.cpython-(\d\d\d)-', so_file)
            if match:
                _ = match.group(1)
                return f'{_[0]}.{_[1:3]}'
        return None

    ##############################################

    # hardlink_count
    @property
    def nlink(self) -> int:
        if self._nlink is None:
            path = self.path / (self.name + '.py')
            if not path.exists():
                path = self.path / self.name / '__init__.py'
            if not path.exists():
                path = self.path / f'{self.name}-{self.version}.dist-info/METADATA'
            return PathInode(path).nlink
        return self._nlink

    ##############################################

    def __repr__(self) -> str:
        return f"Archive Package {self.name} - {self.version}"

####################################################################################################

class SdistPackage(PackageVersion):
    """Implements a Python Package"""

    # /package_name/version/uuid/
    #   package-version-cp315-cp315-linux_x86_64 symlink to archive-v0/uuid
    #   package-version-cp315-cp315-linux_x86_64.whl
    #   src

    ##############################################

    def __init__(self, path: Path) -> None:
        name = path.parent.name
        version = path.name
        super().__init__(path, name, version)

    ##############################################

    def _get_py_version(self) -> str | None:
        SUFFIX = '.whl'
        wheel = None
        for root, dirnames, filenames in self.path.walk():
            for filename in filenames:
                if filename.endswith(SUFFIX):
                    wheel = filename
                    break
        if wheel is not None:
            match = re.match(r'^.*-cp(\d\d\d)-', wheel)
            if match:
                _ = match.group(1)
                return f'{_[0]}.{_[1:3]}'
        return None

    ##############################################

    def __repr__(self) -> str:
        return f"Sdist Package {self.name} - {self.version} - {self.py_version}"

####################################################################################################

class VenvFinder:

    ##############################################

    def __init__(self, path: Path | str, max_py: int) -> None:
        path = Path(path)
        self._max_py = max_py
        self._paths: list[Path] = []
        if path.is_dir():
            self._find(path)
        else:
            self.load_paths(path)
            for _ in self._paths:
                self.on_venv(_)

    ##############################################

    def save_paths(self, path: Path | str) -> None:
        path = Path(path)
        data = {
            'paths': sorted([str(_) for _ in self._paths])
        }
        path.write_text(json.dumps(data, indent=True))

    ##############################################

    def load_paths(self, path: Path | str) -> None:
        path = Path(path)
        C.print(f"Load {path}")
        data = json.loads(path.read_text())
        self._paths = [Path(_) for _ in data['paths']]

    ##############################################

    def _find(self, path: Path) -> None:
        with C.status(f"Searching .venv in {path}..."):
            for root, dirnames, filenames in path.walk():
                match root.name:
                    case '.pycache':
                        dirnames.clear()
                    case '.venv':
                        _ = root.parent
                        self._paths.append(_)
                        self.on_venv(_)
                    case _:
                        if root.name.startswith('.pycache'):
                            dirnames.clear()
            dirnames.sort()  # Fixme: unicode

    ##############################################

    def on_venv(self, path: Path) -> None:
        # self._paths.append(path)
        project = Project(path)
        if project.py_version_int <= self._max_py:
            C.rule()
            C.print(path)
            C.print(f"  Python version is {project.py_version}")
            for dependency in sorted(project.dependencies, key=lambda _: _.name):
                C.print(f"  {dependency}")
                if dependency.latest is not None and dependency.name in TO_UPDATE:
                    dependency.update_to_latest()

####################################################################################################

class Dependency:

    ##############################################

    def __init__(self, project: 'Project', name: str, version: str, tail: str) -> None:
        self.project = project
        self.name = name
        self.version = version
        self.tail = tail

        self.latest: str| None = None
        self.group: str| None = None
        if tail:
            parts = [
                _.replace('(', '').replace(')', '')
                for _ in tail.split(') (')
            ]
            for part in parts:
                if ':' in part:
                    key, value = part.split(': ')
                    setattr(self, key, value)

    ##############################################

    def __repr__(self) -> str:
        color = 'red' if self.latest is not None else 'green'
        return f"[{color}]{self.name}[/] - {self.version} - {self.tail}"

    ##############################################

    def update_to_latest(self) -> None:
        C.print(f"    [red]update[/] {self.name}")
        # uv sync --upgrade-package
        group = '--dev' if self.group == 'dev' else ''
        cmd = f'uv add {group} {self.name}=={self.latest}'
        # f'uv tree -P {self.name}',
        # f'uv sync --upgrade-package {self.name}',
        C.print(f"    {cmd}")
        # try:
        process = subprocess.run(
            cmd,
            shell=True,
            cwd=self.project.path,
            # check=True,
            capture_output=True,
        )
        for _ in (process.stdout, process.stderr):
            C.print(_.decode('utf8'))
        # except subprocess.CalledProcessError:
        #     pass

####################################################################################################

class Project:

    ##############################################

    def __init__(self, path: Path) -> None:
        self.path = path
        self.dependencies: list[Dependency] = []

        try:
            _ = (path / '.python-version').read_text().strip()
            pattern = '/python'
            i = _.find(pattern)
            if i != -1:
                _ = _[i + len(pattern):]
            self.py_version = _
        except FileNotFoundError:
            self.py_version = None

        # 'uv.lock'
        process = subprocess.run(
            'uv tree --outdated',
            shell=True,
            cwd=path,
            check=True,
            capture_output=True,
        )
        stdout = process.stdout.decode('utf8')
        for line in stdout.splitlines():
            if line[0] in '├└─':
                _, name, version , *tail= line.split(' ')
                _ = Dependency(self, name, version, ' '.join(tail))
                self.dependencies.append(_)

    ##############################################

    @property
    def py_version_int(self) -> int:
        _ = self.py_version
        if _:
            return int(_[0] + _[2:])
        else:  # Fixme:
            return 0

####################################################################################################

def list_command() -> None:
    uv_cache = UvCache(CACHE_DIR)
    uv_cache.list()

####################################################################################################

def cache_size_command(prune: bool, min_size: int) -> None:
    # use shell to find uv
    if prune:
        subprocess.check_call('uv cache prune', shell=True)

    uv_cache = UvCache(CACHE_DIR)
    uv_cache.compute_size(min_size)

####################################################################################################

def find_venv_command(path: Path | str, max_py: int) -> None:
    path = Path(path)
    finder = VenvFinder(path, max_py)
    # finder.save_paths('venv-list.json')

####################################################################################################

parser = argparse.ArgumentParser(
    prog='uv-cache-tool',
    description='',
    epilog='',
)
parser.add_argument(
    '--list',
    action='store_true',
)
parser.add_argument(
    '--cache-size',
    action='store_true',
)
parser.add_argument(
    '--find-venv',
)
parser.add_argument(
    '--min-size',
    default=None,
    type=str,
)
parser.add_argument(
    '--max-py',
    default=400,
    type=int,
)
args = parser.parse_args()

####################################################################################################

# Fixme: better ?
if args.list:
    list_command()
elif args.cache_size:
    min_size_str = args.min_size
    if min_size_str is None:
        min_size = 0
    else:
        re_match = re.match(r'(\d+)(MB|GB)', min_size_str)
        if re_match:
            value = int(re_match.group(1))
            match re_match.group(2):
                case 'MB':
                    min_size = value * 1024**2
                case 'GB':
                    min_size = value * 1024**3
        else:
            raise ValueError(f"invalid value {min_size_str}")
    cache_size_command(prune=False, min_size=min_size)
elif args.find_venv:
    find_venv_command(args.find_venv, args.max_py)
else:
    parser.print_help()
